<?php

namespace Filament\Support\Icons;

use Filament\Support\Contracts\Iconizable;

class HeroIcon implements Iconizable
{
    public string $solid = 'o';

    const ACADEMIC_CAP = 'academic-cap';
    const ADJUSTMENTS_HORIZONTAL = 'adjustments-horizontal';
    const ADJUSTMENTS_VERTICAL = 'adjustments-vertical';
    const ARCHIVE_BOX_ARROW_DOWN = 'archive-box-arrow-down';
    const ARCHIVE_BOX_X_MARK = 'archive-box-x-mark';
    const ARCHIVE_BOX = 'archive-box';
    const ARROW_DOWN_CIRCLE = 'arrow-down-circle';
    const ARROW_DOWN_LEFT = 'arrow-down-left';
    const ARROW_DOWN_ON_SQUARE_STACK = 'arrow-down-on-square-stack';
    const ARROW_DOWN_ON_SQUARE = 'arrow-down-on-square';
    const ARROW_DOWN_RIGHT = 'arrow-down-right';
    const ARROW_DOWN_TRAY = 'arrow-down-tray';
    const ARROW_DOWN = 'arrow-down';
    const ARROW_LEFT_CIRCLE = 'arrow-left-circle';
    const ARROW_LEFT_END_ON_RECTANGLE = 'arrow-left-end-on-rectangle';
    const ARROW_LEFT_START_ON_RECTANGLE = 'arrow-left-start-on-rectangle';
    const ARROW_LEFT = 'arrow-left';
    const ARROW_LONG_DOWN = 'arrow-long-down';
    const ARROW_LONG_LEFT = 'arrow-long-left';
    const ARROW_LONG_RIGHT = 'arrow-long-right';
    const ARROW_LONG_UP = 'arrow-long-up';
    const ARROW_PATH_ROUNDED_SQUARE = 'arrow-path-rounded-square';
    const ARROW_PATH = 'arrow-path';
    const ARROW_RIGHT_CIRCLE = 'arrow-right-circle';
    const ARROW_RIGHT_END_ON_RECTANGLE = 'arrow-right-end-on-rectangle';
    const ARROW_RIGHT_START_ON_RECTANGLE = 'arrow-right-start-on-rectangle';
    const ARROW_RIGHT = 'arrow-right';
    const ARROW_TOP_RIGHT_ON_SQUARE = 'arrow-top-right-on-square';
    const ARROW_TRENDING_DOWN = 'arrow-trending-down';
    const ARROW_TRENDING_UP = 'arrow-trending-up';
    const ARROW_UP_CIRCLE = 'arrow-up-circle';
    const ARROW_UP_LEFT = 'arrow-up-left';
    const ARROW_UP_ON_SQUARE_STACK = 'arrow-up-on-square-stack';
    const ARROW_UP_ON_SQUARE = 'arrow-up-on-square';
    const ARROW_UP_RIGHT = 'arrow-up-right';
    const ARROW_UP_TRAY = 'arrow-up-tray';
    const ARROW_UP = 'arrow-up';
    const ARROW_UTURN_DOWN = 'arrow-uturn-down';
    const ARROW_UTURN_LEFT = 'arrow-uturn-left';
    const ARROW_UTURN_RIGHT = 'arrow-uturn-right';
    const ARROW_UTURN_UP = 'arrow-uturn-up';
    const ARROWS_POINTING_IN = 'arrows-pointing-in';
    const ARROWS_POINTING_OUT = 'arrows-pointing-out';
    const ARROWS_RIGHT_LEFT = 'arrows-right-left';
    const ARROWS_UP_DOWN = 'arrows-up-down';
    const AT_SYMBOL = 'at-symbol';
    const BACKSPACE = 'backspace';
    const BACKWARD = 'backward';
    const BANKNOTES = 'banknotes';
    const BARS_2 = 'bars-2';
    const BARS_3_BOTTOM_LEFT = 'bars-3-bottom-left';
    const BARS_3_BOTTOM_RIGHT = 'bars-3-bottom-right';
    const BARS_3_CENTER_LEFT = 'bars-3-center-left';
    const BARS_3 = 'bars-3';
    const BARS_4 = 'bars-4';
    const BARS_ARROW_DOWN = 'bars-arrow-down';
    const BARS_ARROW_UP = 'bars-arrow-up';
    const BATTERY_0 = 'battery-0';
    const BATTERY_100 = 'battery-100';
    const BATTERY_50 = 'battery-50';
    const BEAKER = 'beaker';
    const BELL_ALERT = 'bell-alert';
    const BELL_SLASH = 'bell-slash';
    const BELL_SNOOZE = 'bell-snooze';
    const BELL = 'bell';
    const BOLT_SLASH = 'bolt-slash';
    const BOLT = 'bolt';
    const BOOK_OPEN = 'book-open';
    const BOOKMARK_SLASH = 'bookmark-slash';
    const BOOKMARK_SQUARE = 'bookmark-square';
    const BOOKMARK = 'bookmark';
    const BRIEFCASE = 'briefcase';
    const BUG_ANT = 'bug-ant';
    const BUILDING_LIBRARY = "building-library";
    const BUILDING_OFFICE_2 = "building-office-2";
    const BUILDING_OFFICE = "building-office";
    const BUILDING_STOREFRONT = "building-storefront";
    const CAKE = "cake";
    const CALCULATOR = "calculator";
    const CALENDAR_DAYS = "calendar-days";
    const CALENDAR = "calendar";
    const CHART_BAR_SQUARE = "chart-bar-square";
    const CHART_BAR = "chart-bar";
    const CHART_PIE = "chart-pie";
    const CHECK_BADGE = "check-badge";
    const CHECK_CIRCLE = "check-circle";
    const CHECK = "check";
    const CHEVRON_DOUBLE_DOWN = "chevron-double-down";
    const CHEVRON_DOUBLE_LEFT = "chevron-double-left";
    const CHEVRON_DOUBLE_RIGHT = "chevron-double-right";
    const CHEVRON_DOUBLE_UP = "chevron-double-up";
    const CHEVRON_DOWN = "chevron-down";
    const CHEVRON_LEFT = "chevron-left";
    const CHEVRON_RIGHT = "chevron-right";
    const CHEVRON_UP = "chevron-up";
    const CLOCK = "clock";
    const CLOUD_ARROW_DOWN = "cloud-arrow-down";
    const CLOUD_ARROW_UP = "cloud-arrow-up";
    const CLOUD = "cloud";
    const CODE_BRACKET_SQUARE = "code-bracket-square";
    const CODE_BRACKET = "code-bracket";
    const COG_6_TOOTH = "cog-6-tooth";
    const COG_8_TOOTH = "cog-8-tooth";
    const COG = "cog";
    const COMMAND_LINE = "command-line";
    const COMPUTER_DESKTOP = "computer-desktop";
    const CPU_CHIP = "cpu-chip";
    const CREDIT_CARD = "credit-card";
    const CUBE_TRANSPARENT = "cube-transparent";
    const CUBE = "cube";
    const CURRENCY_BANGLADESHI = "currency-bangladeshi";
    const CURRENCY_DOLLAR = "currency-dollar";
    const CURRENCY_EURO = "currency-euro";
    const CURRENCY_POUND = "currency-pound";
    const CURRENCY_RUPEE = "currency-rupee";
    const CURRENCY_YEN = "currency-yen";
    const CURSOR_ARROW_RAYS = "cursor-arrow-rays";
    const CURSOR_ARROW_RIPPLE = "cursor-arrow-ripple";
    const DEVICE_PHONE_MOBILE = "device-phone-mobile";
    const DEVICE_TABLET = "device-tablet";
    const DOCUMENT_ARROW_DOWN = "document-arrow-down";
    const DOCUMENT_ARROW_UP = "document-arrow-up";
    const DOCUMENT_CHART_BAR = "document-chart-bar";
    const DOCUMENT_CHECK = "document-check";
    const DOCUMENT_DUPLICATE = "document-duplicate";
    const DOCUMENT_MAGNIFYING_GLASS = "document-magnifying-glass";
    const DOCUMENT_MINUS = "document-minus";
    const DOCUMENT_PLUS = "document-plus";
    const DOCUMENT_TEXT = "document-text";
    const DOCUMENT = "document";
    const ELLIPSIS_HORIZONTAL_CIRCLE = "ellipsis-horizontal-circle";
    const ELLIPSIS_HORIZONTAL = "ellipsis-horizontal";
    const ELLIPSIS_VERTICAL = "ellipsis-vertical";
    const ENVELOPE_OPEN = "envelope-open";
    const ENVELOPE = "envelope";
    const EXCLAMATION_CIRCLE = "exclamation-circle";
    const EXCLAMATION_TRIANGLE = "exclamation-triangle";
    const EYE_DROPPER = "eye-dropper";
    const EYE_SLASH = "eye-slash";
    const EYE = "eye";
    const FACE_FROWN = "face-frown";
    const FACE_SMILE = "face-smile";
    const FILM = "film";
    const FINGER_PRINT = "finger-print";
    const FIRE = "fire";
    const FLAG = "flag";
    const FOLDER_ARROW_DOWN = "folder-arrow-down";
    const FOLDER_MINUS = "folder-minus";
    const FOLDER_OPEN = "folder-open";
    const FOLDER_PLUS = "folder-plus";
    const FOLDER = "folder";
    const FORWARD = "forward";
    const FUNNEL = "funnel";
    const GIF = "gif";
    const GIFT_TOP = "gift-top";
    const GIFT = "gift";
    const GLOBE_ALT = "globe-alt";
    const GLOBE_AMERICAS = "globe-americas";
    const GLOBE_ASIA_AUSTRALIA = "globe-asia-australia";
    const GLOBE_EUROPE_AFRICA = "globe-europe-africa";
    const HAND_RAISED = "hand-raised";
    const HAND_THUMB_DOWN = "hand-thumb-down";
    const HAND_THUMB_UP = "hand-thumb-up";
    const HASHTAG = "hashtag";
    const HEART = "heart";
    const HOME_MODERN = "home-modern";
    const HOME = "home";
    const IDENTIFICATION = "identification";
    const INBOX_ARROW_DOWN = 'inbox-arrow-down';
    const INBOX_STACK = 'inbox-stack';
    const INBOX = 'inbox';
    const INFORMATION_CIRCLE = 'information-circle';
    const KEY = 'key';
    const LANGUAGE = 'language';
    const LIFEBUOY = 'lifebuoy';
    const LIGHT_BULB = 'light-bulb';
    const LINK = 'link';
    const LIST_BULLET = 'list-bullet';
    const LOCK_CLOSED = 'lock-closed';
    const LOCK_OPEN = 'lock-open';
    const MAGNIFYING_GLASSES_CIRCLE = 'magnifying-glasses-circle';
    const MAGNIFYING_GLASSES_MINUS = 'magnifying-glasses-minus';
    const MAGNIFYING_GLASSES_PLUS = 'magnifying-glasses-plus';
    const MAGNIFYING_GLASSES = 'magnifying-glasses';
    const MAP_PIN = 'map-pin';
    const MAP = 'map';
    const MEGAPHONE = 'megaphone';
    const MICROPHONE = 'microphone';
    const MINUS_CIRCLE = 'minus-circle';
    const MINUS = 'minus';
    const MOON = 'moon';
    const MUSICAL_NOTE = 'musical-note';
    const NEWSPAPER = 'newspaper';
    const NO_SYMBOL = 'no-symbol';
    const PAINT_BRUSH = 'paint-brush';
    const PAPER_AIRPLANE = 'paper-airplane';
    const PAPER_CLIP = 'paper-clip';
    const PAUSE_CIRCLE = 'pause-circle';
    const PAUSE = 'pause';
    const PENCIL_SQUARE = 'pencil-square';
    const PENCIL = 'pencil';
    const PHONE_ARROW_DOWN_LEFT = 'phone-arrow-down-left';
    const PHONE_ARROW_UP_RIGHT = 'phone-arrow-up-right';
    const PHONE_X_MARK = 'phone-x-mark';
    const PHONE = 'phone';
    const PHOTO = 'photo';
    const PLAY_CIRCLE = 'play-circle';
    const PLAY_PAUSE = 'play-pause';
    const PLAY = 'play';
    const PLUS_CIRCLE = 'plus-circle';
    const PLUS = 'plus';
    const POWER = 'power';
    const PRESENTATION_CHART_BAR = 'presentation-chart-bar';
    const PRESENTATION_CHART_LINE = 'presentation-chart-line';
    const PRINTER = 'printer';
    const PUZZLE_PIECE = 'puzzle-piece';
    const QR_CODE = 'qr-code';
    const QUESTION_MARK_CIRCLE = 'question-mark-circle';
    const QUEUE_LIST = "queue-list";
    const RADIO = "radio";
    const RECEIPT_PERCENT = "receipt-percent";
    const RECEIPT_REFUND = "receipt-refund";
    const RECTANGLE_GROUP = "rectangle-group";
    const RECTANGLE_STACK = "rectangle-stack";
    const ROCKET_LAUNCH = "rocket-launch";
    const RSS = "rss";
    const SCALE = "scale";
    const SCISSORS = "scissors";
    const SERVER_STACK = "server-stack";
    const SERVER = "server";
    const SHARE = "share";
    const SHIELD_CHECK = "shield-check";
    const SHIELD_EXCLAMATION = "shield-exclamation";
    const SHOPPING_BAG = "shopping-bag";
    const SHOPPING_CART = "shopping-cart";
    const SIGNAL_SLASH = "signal-slash";
    const SIGNAL = "signal";
    const SPARKLES = "sparkles";
    const SPEAKER_WAVE = "speaker-wave";
    const SPEAKER_X_MARK = "speaker-x-mark";
    const SQUARE_2_STACK = "square-2-stack";
    const SQUARE_3_STACK_3D = "square-3-stack-3d";
    const SQUARES_2X2 = "squares-2x2";
    const SQUARES_PLUS = "squares-plus";
    const STAR = "star";
    const STOP_CIRCLE = "stop-circle";
    const STOP = "stop";
    const SUN = "sun";
    const SWATCH = "swatch";
    const TABLE_CELLS = "table-cells";
    const TAG = "tag";
    const TICKET = "ticket";
    const TRASH = "trash";
    const TROPHY = "trophy";
    const TRUCK = "truck";
    const TV = "tv";
    const USER_CIRCLE = "user-circle";
    const USER_GROUP = "user-group";
    const USER_MINUS = "user-minus";
    const USER_PLUS = "user-plus";
    const USER = "user";
    const USERS = "users";
    const VARIABLE = "variable";
    const VIDEO_CAMERA_SLASH = "video-camera-slash";
    const VIDEO_CAMERA = "video-camera";
    const VIEW_COLUMNS = "view-columns";
    const VIEWFINDER_CIRCLE = "viewfinder-circle";
    const WALLET = "wallet";
    const WIFI = "wifi";
    const WINDOW = "window";
    const WRENCH_SCREWDRIVER = "wrench-screwdriver";
    const WRENCH = "wrench";
    const X_CIRCLE = "x-circle";
    const X_MARK = "x-mark";



    public function __construct(public string $icon = 'rectangle-stack') {}

    public static function make(string $icon): static
    {
        $static = app(static::class, ['icon' => $icon]);

        return $static;
    }

    public function solid()
    {
        $this->solid = 's';
        return $this;
    }

    public function getIconName(): string
    {
        $type = $this->solid;

        return "heroicon-{$type}-{$this->icon}";
    }
}
