version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    cooldown:
      default-days: 7
    labels:
      - dependencies
    milestone: 9

  - package-ecosystem: github-actions
    directory: /
    target-branch: 5.x
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    cooldown:
      default-days: 7
    labels:
      - dependencies
    milestone: 10

  - package-ecosystem: github-actions
    directory: /
    target-branch: 3.x
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    cooldown:
      default-days: 7
    labels:
      - dependencies
    milestone: 2

  - package-ecosystem: github-actions
    directory: /
    target-branch: 2.x
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    cooldown:
      default-days: 7
    labels:
      - dependencies
    milestone: 1
