#!/usr/bin/env bash

set -e

source "scripts/filament-issue.sh"

function help {
    echo "$0 <task> <args>"
    echo "Tasks:"
    compgen -A function | cat -n
}

function default {
    help
}

TIMEFORMAT="Task completed in %3lR"
time "${@:-default}"
