import 'easymde/dist/easymde.min.css'
import 'cropperjs/dist/cropper.min.css'
import 'filepond/dist/filepond.min.css'
import 'filepond-plugin-image-edit/dist/filepond-plugin-image-edit.css'
import 'filepond-plugin-image-preview/dist/filepond-plugin-image-preview.css'
import '../css/components/file-upload/filepond-plugin-media-preview.css'
import 'nouislider/dist/nouislider.css'
