<x-filament::stats.card
    :chart="$getChart()"
    :chart-color="$getChartColor()"
    :color="$getColor()"
    :description="$getDescription()"
    :description-color="$getDescriptionColor()"
    :description-icon="$getDescriptionIcon()"
    :label="$getLabel()"
    :value="$getValue()"
    class="filament-stats-overview-widget-card"
/>
