<x-filament::icon-button
    color="gray"
    icon-alias="tables::reorder.handle"
    icon="heroicon-m-arrows-up-down"
    :attributes="
        \Filament\Support\prepare_inherited_attributes($attributes)
            ->class(['-m-2'])
    "
/>
