<x-filament::icon-button
    color="gray"
    icon="heroicon-m-bars-2"
    :icon-alias="'tables::reorder.handle'"
    :attributes="
        \Filament\Support\prepare_inherited_attributes($attributes)
            ->class(['fi-ta-reorder-handle'])
    "
/>
