<x-filament-actions::group
    :actions="$getActions()"
    :dark-mode="config('tables.dark_mode')"
    :color="$getColor()"
    :dropdown-placement="$getDropdownPlacement()"
    :icon="$getIcon()"
    :label="$getLabel()"
    :size="$getSize()"
    :tooltip="$getTooltip()"
/>
