const defaultTheme = require('tailwindcss/defaultTheme')

module.exports = {
    content: ['./vendor/filament/**/*.blade.php'],
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                danger: {
                    50: 'rgba(--danger-color-50, <alpha-value>)',
                    100: 'rgba(--danger-color-100, <alpha-value>)',
                    200: 'rgba(--danger-color-200, <alpha-value>)',
                    300: 'rgba(--danger-color-300, <alpha-value>)',
                    400: 'rgba(--danger-color-400, <alpha-value>)',
                    500: 'rgba(--danger-color-500, <alpha-value>)',
                    600: 'rgba(--danger-color-600, <alpha-value>)',
                    700: 'rgba(--danger-color-700, <alpha-value>)',
                    800: 'rgba(--danger-color-800, <alpha-value>)',
                    900: 'rgba(--danger-color-900, <alpha-value>)',
                    950: 'rgba(--danger-color-950, <alpha-value>)',
                },
                gray: {
                    50: 'rgba(--gray-color-50, <alpha-value>)',
                    100: 'rgba(--gray-color-100, <alpha-value>)',
                    200: 'rgba(--gray-color-200, <alpha-value>)',
                    300: 'rgba(--gray-color-300, <alpha-value>)',
                    400: 'rgba(--gray-color-400, <alpha-value>)',
                    500: 'rgba(--gray-color-500, <alpha-value>)',
                    600: 'rgba(--gray-color-600, <alpha-value>)',
                    700: 'rgba(--gray-color-700, <alpha-value>)',
                    800: 'rgba(--gray-color-800, <alpha-value>)',
                    900: 'rgba(--gray-color-900, <alpha-value>)',
                    950: 'rgba(--gray-color-950, <alpha-value>)',
                },
                primary: {
                    50: 'rgba(--primary-color-50, <alpha-value>)',
                    100: 'rgba(--primary-color-100, <alpha-value>)',
                    200: 'rgba(--primary-color-200, <alpha-value>)',
                    300: 'rgba(--primary-color-300, <alpha-value>)',
                    400: 'rgba(--primary-color-400, <alpha-value>)',
                    500: 'rgba(--primary-color-500, <alpha-value>)',
                    600: 'rgba(--primary-color-600, <alpha-value>)',
                    700: 'rgba(--primary-color-700, <alpha-value>)',
                    800: 'rgba(--primary-color-800, <alpha-value>)',
                    900: 'rgba(--primary-color-900, <alpha-value>)',
                    950: 'rgba(--primary-color-950, <alpha-value>)',
                },
                secondary: {
                    50: 'rgba(--secondary-color-50, <alpha-value>)',
                    100: 'rgba(--secondary-color-100, <alpha-value>)',
                    200: 'rgba(--secondary-color-200, <alpha-value>)',
                    300: 'rgba(--secondary-color-300, <alpha-value>)',
                    400: 'rgba(--secondary-color-400, <alpha-value>)',
                    500: 'rgba(--secondary-color-500, <alpha-value>)',
                    600: 'rgba(--secondary-color-600, <alpha-value>)',
                    700: 'rgba(--secondary-color-700, <alpha-value>)',
                    800: 'rgba(--secondary-color-800, <alpha-value>)',
                    900: 'rgba(--secondary-color-900, <alpha-value>)',
                    950: 'rgba(--secondary-color-950, <alpha-value>)',
                },
                warning: {
                    50: 'rgba(--warning-color-50, <alpha-value>)',
                    100: 'rgba(--warning-color-100, <alpha-value>)',
                    200: 'rgba(--warning-color-200, <alpha-value>)',
                    300: 'rgba(--warning-color-300, <alpha-value>)',
                    400: 'rgba(--warning-color-400, <alpha-value>)',
                    500: 'rgba(--warning-color-500, <alpha-value>)',
                    600: 'rgba(--warning-color-600, <alpha-value>)',
                    700: 'rgba(--warning-color-700, <alpha-value>)',
                    800: 'rgba(--warning-color-800, <alpha-value>)',
                    900: 'rgba(--warning-color-900, <alpha-value>)',
                    950: 'rgba(--warning-color-950, <alpha-value>)',
                },
                success: {
                    50: 'rgba(--success-color-50, <alpha-value>)',
                    100: 'rgba(--success-color-100, <alpha-value>)',
                    200: 'rgba(--success-color-200, <alpha-value>)',
                    300: 'rgba(--success-color-300, <alpha-value>)',
                    400: 'rgba(--success-color-400, <alpha-value>)',
                    500: 'rgba(--success-color-500, <alpha-value>)',
                    600: 'rgba(--success-color-600, <alpha-value>)',
                    700: 'rgba(--success-color-700, <alpha-value>)',
                    800: 'rgba(--success-color-800, <alpha-value>)',
                    900: 'rgba(--success-color-900, <alpha-value>)',
                    950: 'rgba(--success-color-950, <alpha-value>)',
                },
            },
            fontFamily: {
                sans: ['--font-family', ...defaultTheme.fontFamily.sans],
            },
        },
    },
    plugins: [
        require('@tailwindcss/forms'),
        require('@tailwindcss/typography'),
    ],
}
