<x-filament::field-group
    :errorKey="$field->errorKey"
    :for="$field->id"
    :help="__($field->help)"
    :hint="__($field->hint)"
    :label="__($field->label)"
    :required="$field->required"
>
    <x-slot name="labelPrefix">
        <x-filament::checkbox
            :autofocus="$field->autofocus"
            :disabled="$field->disabled"
            :error-key="$field->errorKey"
            :extra-attributes="$field->attributes"
            :id="$field->id"
            :name="$field->name"
            :name-attribute="$field->nameAttribute"
            :required="$field->required"
        />
    </x-slot>
</x-filament::field-group>
