<x-filament::field-group
    :errorKey="$field->errorKey"
    :for="$field->id"
    :help-message="__($field->helpMessage)"
    :hint="__($field->hint)"
    :label="__($field->label)"
    :required="$field->required"
>
    <x-filament::date-time-picker
        :autofocus="$field->autofocus"
        :disabled="$field->disabled"
        :display-format="$field->displayFormat"
        :error-key="$field->errorKey"
        :extra-attributes="$field->extraAttributes"
        :format="$field->format"
        :id="$field->id"
        :max="$field->max"
        :min="$field->min"
        :name="$field->name"
        :name-attribute="$field->nameAttribute"
        :placeholder="__($field->placeholder)"
        :required="$field->required"
        :time="$field->time"
    />
</x-filament::field-group>
