<x-filament::field-group
    :errorKey="$field->errorKey"
    :for="$field->id"
    :help="$field->help"
    :hint="$field->hint"
    :label="$field->label"
    :required="$field->required"
>
    <x-filament::select
        :id="$field->id"
        :model-directive="$field->modelDirective"
        :name="$field->name"
        :error-key="$field->errorKey"
        :extra-attributes="$field->attributes"
        :required="$field->required"
        :placeholder="__($field->placeholder)"
        :options="$field->options"
    />
</x-filament::field-group>
