<x-filament::field-group
    :errorKey="$field->errorKey"
    :for="$field->id"
    :help-message="__($field->helpMessage)"
    :hint="__($field->hint)"
    :label="__($field->label)"
    :required="$field->required"
>
    <x-filament::select
        :id="$field->id"
        :name="$field->name"
        :name-attribute="$field->nameAttribute"
        :error-key="$field->errorKey"
        :extra-attributes="$field->extraAttributes"
        :required="$field->required"
        :placeholder="__($field->placeholder)"
        :options="$field->options"
    />
</x-filament::field-group>
