<x-filament::field-group
    :errorKey="$field->errorKey"
    :for="$field->id"
    :help="$field->help"
    :hint="$field->hint"
    :label="$field->label"
    :required="$field->required"
>
    <x-filament::input
        :autocomplete="$field->autocomplete"
        :autofocus="$field->autofocus"
        :disabled="$field->disabled"
        :error-key="$field->errorKey"
        :extra-attributes="$field->attributes"
        :id="$field->id"
        :maxLength="$field->maxLength"
        :minLength="$field->minLength"
        :model-directive="$field->modelDirective"
        :name="$field->name"
        :placeholder="__($field->placeholder)"
        :required="$field->required"
        :type="$field->type"
    />
</x-filament::field-group>
