<x-forms::field-group
    :column-span="$field->columnSpan"
    :error-key="$field->name"
    :for="$field->id"
    :help-message="__($field->helpMessage)"
    :hint="__($field->hint)"
    :label="__($field->label)"
    :required="$field->required"
>
    <x-forms::select
        :autofocus="$field->autofocus"
        :disabled="$field->disabled"
        :empty-options-message="__($field->emptyOptionsMessage)"
        :error-key="$field->name"
        :extra-attributes="$field->extraAttributes"
        :id="$field->id"
        :name="$field->name"
        :name-attribute="$field->nameAttribute"
        :no-search-results-message="__($field->noSearchResultsMessage)"
        :options="$field->options"
        :placeholder="__($field->placeholder)"
        :required="$field->required"
    />
</x-forms::field-group>
