const colors = require('tailwindcss/colors')
const defaultTheme = require('tailwindcss/defaultTheme')

module.exports = {
    mode: 'jit',
    purge: [
        './packages/admin/resources/**/*.blade.php',
        './packages/forms/resources/**/*.blade.php',
        './packages/tables/resources/**/*.blade.php',
    ],
    theme: {
        extend: {
            colors: {
                danger: {
                    50: 'var(--f-danger-50)',
                    100: 'var(--f-danger-100)',
                    200: 'var(--f-danger-200)',
                    300: 'var(--f-danger-300)',
                    400: 'var(--f-danger-400)',
                    500: 'var(--f-danger-500)',
                    600: 'var(--f-danger-600)',
                    700: 'var(--f-danger-700)',
                    800: 'var(--f-danger-800)',
                    900: 'var(--f-danger-900)',
                },
                gray: {
                    50: 'var(--f-gray-50)',
                    100: 'var(--f-gray-100)',
                    200: 'var(--f-gray-200)',
                    300: 'var(--f-gray-300)',
                    400: 'var(--f-gray-400)',
                    500: 'var(--f-gray-500)',
                    600: 'var(--f-gray-600)',
                    700: 'var(--f-gray-700)',
                    800: 'var(--f-gray-800)',
                    900: 'var(--f-gray-900)',
                },
                primary: {
                    50: 'var(--f-primary-50)',
                    100: 'var(--f-primary-100)',
                    200: 'var(--f-primary-200)',
                    300: 'var(--f-primary-300)',
                    400: 'var(--f-primary-400)',
                    500: 'var(--f-primary-500)',
                    600: 'var(--f-primary-600)',
                    700: 'var(--f-primary-700)',
                    800: 'var(--f-primary-800)',
                    900: 'var(--f-primary-900)',
                },
                success: {
                    50: 'var(--f-success-50)',
                    100: 'var(--f-success-100)',
                    200: 'var(--f-success-200)',
                    300: 'var(--f-success-300)',
                    400: 'var(--f-success-400)',
                    500: 'var(--f-success-500)',
                    600: 'var(--f-success-600)',
                    700: 'var(--f-success-700)',
                    800: 'var(--f-success-800)',
                    900: 'var(--f-success-900)',
                },
                warning: {
                    50: 'var(--f-warning-50)',
                    100: 'var(--f-warning-100)',
                    200: 'var(--f-warning-200)',
                    300: 'var(--f-warning-300)',
                    400: 'var(--f-warning-400)',
                    500: 'var(--f-warning-500)',
                    600: 'var(--f-warning-600)',
                    700: 'var(--f-warning-700)',
                    800: 'var(--f-warning-800)',
                    900: 'var(--f-warning-900)',
                },
                defaultDanger: colors.rose,
                defaultGray: colors.warmGray,
                defaultPrimary: colors.yellow,
                defaultSuccess: colors.green,
                defaultWarning: colors.amber,
            },
            fontFamily: {
                mono: ['JetBrains Mono', ...defaultTheme.fontFamily.mono],
                sans: ['DM Sans', ...defaultTheme.fontFamily.sans],
            },
        },
    },
    plugins: [
        require('@tailwindcss/forms'),
        require('@tailwindcss/typography'),
    ],
}
