name: monorepo-split

on:
  push:
    tags: '*'

permissions:
  contents: read

jobs:
  split-monorepo:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - actions
          - forms
          - infolists
          - notifications
          - panels
          - query-builder
          - schemas
          - spark-billing-provider
          - spatie-laravel-google-fonts-plugin
          - spatie-laravel-media-library-plugin
          - spatie-laravel-settings-plugin
          - spatie-laravel-tags-plugin
          - support
          - tables
          - widgets
          - upgrade
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.0
        with:
          persist-credentials: false
      - id: previous-tag
        uses: WyriHaximus/github-action-get-previous-tag@04e8485ecb6487243907e330d522ff60f02283ce # v1.4.0
      - name: Monorepo Split of ${{ matrix.package }}
        uses: danharrin/monorepo-split-github-action@19b2e0cbe3fe3de17309fd0fe95d4e05454f3ab3 # v2.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        with:
          package_directory: 'packages/${{ matrix.package }}'
          repository_organization: 'filamentphp'
          repository_name: '${{ matrix.package }}'
          branch: 4.x
          tag: ${{ steps.previous-tag.outputs.tag }}
          user_name: 'Dan Harrin'
          user_email: 'git@danharrin.com'
