name: monorepo-split

on:
  push:
    tags: '*'

permissions:
  contents: read

jobs:
  split-monorepo:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - actions
          - forms
          - infolists
          - notifications
          - panels
          - query-builder
          - schemas
          - spark-billing-provider
          - spatie-laravel-google-fonts-plugin
          - spatie-laravel-media-library-plugin
          - spatie-laravel-settings-plugin
          - spatie-laravel-tags-plugin
          - support
          - tables
          - widgets
          - upgrade
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - id: previous-tag
        uses: WyriHaximus/github-action-get-previous-tag@61819f33034117e6c686e6a31dba995a85afc9de # v2.0.0
      - name: Monorepo Split of ${{ matrix.package }}
        uses: danharrin/monorepo-split-github-action@14e42e2437f674b8987c1f50ca3689116aea1893 # v2.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        with:
          package_directory: 'packages/${{ matrix.package }}'
          repository_organization: 'filamentphp'
          repository_name: '${{ matrix.package }}'
          branch: 4.x
          tag: ${{ steps.previous-tag.outputs.tag }}
          user_name: 'Dan Harrin'
          user_email: 'git@danharrin.com'
