name: zizmor

on:
  push:
    paths:
      - '.github/workflows/**'
      - '.github/dependabot.yml'
  pull_request:
    paths:
      - '.github/workflows/**'
      - '.github/dependabot.yml'

permissions:
  contents: read

jobs:
  zizmor:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.0
        with:
          persist-credentials: false

      - uses: zizmorcore/zizmor-action@b1d7e1fb5de872772f31590499237e7cce841e8e # v0.5.3
